In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\ADMIN\\AppData\\Roaming\\Python\\Python311\\site-packages\\numpy\\__init__.py'>

In [4]:
_1d_array = np.array([1, 2, 3])
_1d_array

array([1, 2, 3])

In [5]:
_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
all_zeros = np.zeros(5)
all_zeros

array([0., 0., 0., 0., 0.])

In [7]:
all_ones = np.ones(5)
all_ones

array([1., 1., 1., 1., 1.])

In [8]:
arr = np.arange(1, 101, 1)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
arr = np.linspace(1, 10, num=10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
arr = np.ones(5, dtype=np.int64)
arr

array([1, 1, 1, 1, 1], dtype=int64)

In [11]:
arr = np.array([1, 3, 2, 8, 4, 9])
arr

array([1, 3, 2, 8, 4, 9])

In [12]:
arr = np.sort(arr)[::-1]
arr

array([9, 8, 4, 3, 2, 1])

In [13]:
arr = np.append(arr, 100)
arr

array([  9,   8,   4,   3,   2,   1, 100])

In [14]:
arr = np.delete(arr, 5)
arr

array([  9,   8,   4,   3,   2, 100])

In [15]:
arr = np.array([[44, 2, 3], [4, 5, 6]])

arr = np.sort(arr, axis=0)
arr

array([[ 4,  2,  3],
       [44,  5,  6]])

In [16]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6


In [17]:
arr_float = arr.astype(float)
arr_float = arr.astype(float)


In [18]:
arr = np.arange(1, 7, 1)
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
arr_2d = arr.reshape((2,3))
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(arr_2d.flatten())

[1 2 3 4 5 6]


In [21]:
arr[1:4]

array([2, 3, 4])

In [22]:
arr[:-1]

array([1, 2, 3, 4, 5])

In [23]:
arr[-2:]

array([5, 6])

In [24]:
np.dot(arr_2d, arr_2d.T)

array([[14, 32],
       [32, 77]])

In [25]:
print(np.concatenate((arr_2d, arr_2d), axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [27]:
print(np.sum(arr))

21


In [28]:
print(np.mean(arr))

3.5


In [29]:
print(np.max(arr))
print(np.min(arr))

6
1


In [30]:
print(np.std(arr))
print(np.var(arr))

1.707825127659933
2.9166666666666665
